### PR TITLE
Support scores for smol snek

### PR DESCRIPTION
**Pull request by blind**
I copied one of the other folders and modified to parse the smol snek high score table.

### CODE REVIEW

**Comment by tschak909** [comment]
Thank you! :)

**Comment by tschak909** [comment]
@blind should we put a copy in our High Score Enabled folder?
-Thom

**Comment by blind** [comment]
@tschak909 Please do, I would appreciate that. The .atr is already uploaded to the Atari_8-bit/incoming folder on apps.irata.online TNFS server. You can grab it for there and copy it to wherever you like. :)

**Comment by tschak909** [comment]
The game and scraper have been deployed onto apps, and scores.
http://scores.irata.online/

Thank you so much! :)

**Pull request merged**
